[models]

ollama_host = "http://localhost:11434"

model     = "ministral-3:3b"
embedding = "nomic-embed-text"

# model_max_tokens       =
# embedding_max_tokens  =

fallback_tokenizer  = "gpt2"


[memory]

retrieve_entry_limit                        = 3
auto_memory_store_enable_at_model_tokens    = 128000
enable_auto_memory_retrieve                 = true
enable_auto_memory_store                    = true


[file_reader]

auto_read_dropbox_enable_at_model_tokens    = 128000
enable_auto_read_dropbox                    = true
enable_docling                              = true
