[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "agent"
version = "0.1.0"
requires-python = ">=3.11"
dependencies = [
  "ollama>=0.6.1",
  "pdfplumber>=0.11.10",
  "rich>=15.0.0",
  "tiktoken>=0.14.0",
  "beautifulsoup4>=4.15.0",
  "lxml>=6.1.1",
  "openpyxl>=3.1.5",
  "python-docx>=1.2.0",
  "ebooklib>=0.20",
  "docling>=2.120.1",
  "psycopg2>=2.9.12",
  "dotenv>=0.9.9",
  "tokenizers>=0.22.2",
  "langchain-text-splitters>=1.1.2",
  "feedparser>=6.0.14",
  "rich-argparse>=1.8.0",
  "textual>=8.2.8",
  "tomli-w>=1.2.0",
]

[project.scripts]
agent = "main:main"

[tool.setuptools]
py-modules = ["main"]

# Rest of the package code
[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = [".", "src"]
